services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    env_file: .env
    environment:
      - PORT=5001
    ports:
      - "$PORT:$PORT"
    depends_on:
      - postgres
    restart: unless-stopped

  ####################### POSTGRES #######################
  postgres:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'myapp'
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres:
